kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-backups
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/component: database    
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
