apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  labels:
    app: mariadb
    tier: database
data:
  # echo -n 'my-root-password' | base64
  root-password: bXktcm9vdC1wYXNzd29yZA==
  # echo -n 'vmware-password' | base64
  user-password: dm13YXJlLXBhc3N3b3Jk
